spring:
  application:
    name: codesync-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}  # echo -n "my-super-secret-key-that-is-long-enough-32chars" | base64
    expiration-ms: 86400000  # (1 day expiry time) : will implement refresh token in later phases of project

  cors:
    allowed-origins: > #  (https://*.vercel.app) keep till develop only to use setAllowedOriginPatterns instead of setAllowedOrigins
      http://localhost:4200,
      https://codesync-workspace.vercel.app,
      https://*.vercel.app  

