spring:
  application:
    name: codesync-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

#  echo -n "my-super-secret-key-that-is-long-enough-32chars" | base64
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000


